#+TITLE: PHIL 201 Notes
#+AUTHOR: Stephen Brennan
#+OPTIONS: tex:t
#+STARTUP: entitiespretty

* 2015-08-24 Monday

  Context:

  - Socrates - dies 399 BC
  - Plato - writes 15 years after that
  - Aristotle - even younger than that

  What did Socrates write?  We know because of comedies written about him, and
  ideas attributed here.  He would say he couldn't teach you anything, only talk
  about stuff.  He talked about the "good life, not a teacher."  He was the
  enemy of the "sophist," who takes money for teaching.

  What did Plato do?  Dialogues about Socrates, and other stuff.  People copied
  his works for 1500 years, so we have crystal clear knowledge of what he did.
  He also ran the Academy in Athens (where the "right people"--young men--could
  get together and learn).  He coined the term Academy in Greek.  He wrote about
  "The Good".

  Aristotle went to Plato's Academy.  He created Formal Logic, all by himself.
  Here's some of his stuff.

  - All Greeks are mortal.  Socrates is a greek.  Therefore, Socrates is mortal.
  - Some snakes are poisonous.  There's a snake right next to your shoe.
    Therefore, you should move away slowly.

  Differences between the two:

  - The first is a "Universal" and the second is a "Particular" (all/some).
  - The first is "deductively valid".  That means that every argument of this
    form is valid, so long as each of the propositions are true.

  Modern logic came about because of von Neuman, Alonzo Church, and Alan Turing.
  The same guys who created computers.

  This class is about new ways of organizing arguments, not new and clever
  arguments.  We will also learn how to evaluate arguments:

  - Soundness: no false positives.  A sound method could be as simple as never
    answering.
  - Completeness: all correct positives.  A complete method would always say
    yes.
  - Effective: always gives you an answer.

  This logic is:

  1. Utterly precise
  2. Artificial
  3. Simple (but not necessarily easy)
  4. Limited

  The textbook: "The Logic Book" by Merrie Bergman.
* 2015-08-26 Wednesday

** Chapter 1 - Deductive Logic

   "There is no inductive logic."

   A *sentence* is a statement which is True or False.  What is /not/ a sentence
   in our terminology?
   - Interrogatives (questions)
   - Imperatives (commands)
   - (/Future tense, predictions/) - in logic class, these are true or false,
     but there could be lots of lively debate.  Apparently Aristotle wrote about
     this and our instructor says it is a "long and confusing" section.
   - Opinionated statements (e.g. "France is a beautiful country.").  For logic
     textbook purposes, we can treet these as declarative sentences, but we
     don't typically think of them that way in the real world.

   An *argument* is a list of sentences, one of which is called a *conclusion*,
   the others are called *premises*.  There can be discussion about how many
   sentences are required, but really you only need one to have an argument.
   Additionally, the book says in older editions that the premises should be
   "intended to support the conclusion."  But that really shouldn't matter.
   This is missing several parts from normal definitions of arguments:
   - Opposing viewpoints.
   - Reasoning (why a premise supports a conclusion).

   A (Deductively) *valid* argument is an argument where there is no way for the
   premises to be True while the conclusion is False.  Correspondingly, an
   *invalid* argument is one where there is some way for the premises to be True
   and the conclusion False (which is called a *counterexmple*, CE).

   Example Arguments:

   - Today is Wednesday and is not Wednesday.  \therefore, the temperature is 80\deg{}F.
     - Valid.  The premise is never true.  There is no way for the premise to be
       true while the conclusion is false.  *An argument with inconsistent
       premises is trivially valid.*
   - Columbus is capital of Ohio.  \therefore Columbus is in Ohio.
     - Doesn't matter.  This is where the "no way" becomes vague.

* 2015-08-28 Friday

  Sentences $p$ and $q$ are *logically equivalent* if there is no way to make
  one True and the other False.

  EG:
  - It is either not Wednesday or not raining.  (or both)
  - It is not Wednesday and raining.
  - (FYI, DeMorgan's Law)

  Quiz on Wednesday.  What will be on the quiz?  Definitions mostly.
  Definitions we covered up till the quiz.  Which may include chapter 2.

  A list of sentences is *consistent* if there is Some Way for all to be True at
  once.  Satisfiability!!  EG:

  - If today is Wednesday, then it's not raining.
  - Today is Wednesday.
  - It is raining.

  No matter how you did it, you couldn't make all of these true.  So this list
  of sentences is not consistent.

  P_1, P_2, ..., P_n \therefore C is Logically Valid iff the list {P_1, P_2, ..., P_n,
  \not{}C} is inconsistent.

** Chapter 2

   An *atomic* sentence is a sentence with no smaller sentence as part.  A
   *connective* is a word (or words) that applies to one or more sentences to
   form a sentence.  EG:
   - "not" - applies to any sentence, and creates a new sentence.
   - "and" - can go between sentences, and creates a new one
   - "don't say" - is NOT a connective, because it forms an imperative, not a
     sentence.
   - "I don't believe" - is a connective.

   A *Truth Functional Connective* is a connective such that the truth value of
   the sentence it forms is wholly determined by the truth value of the parts.

   - NOT + (Bornite is a Cu ore): this is TFC, because Not always reverses the
     truth value.
   - My Brother Knows + (Bornite is a Cu ore): this is a connective, but not
     TFC, because the sentence alone doesn't tell you whether the whole thing is
     true.

   In other words, TFCs are connectives that have truth tables!!!  EG, for not:

   | P | \not{}P |
   | T | F  |
   | F | T  |
* 2015-08-31 Monday

  - A = it is raining
  - B = it is wednesday
  - \not{}B = not - it is raining

  | A | B | \not{}A | \not\not{}A | A\land{}B | A\lor{}B | A\to{}B | A\equiv{}B |
  | T | T | F  | T   | T   | T   | T   | T   |
  | T | F | F  | T   | F   | T   | F   | F   |
  | F | T | T  | F   | F   | T   | T   | F   |
  | F | F | T  | F   | F   | F   | T   | T   |

  In "King George's English", you may repeat "not" several times to emphasize
  just how much "not" you mean.  EG "I will not not not not not go to class!".
  Also, in English, "or" can mean "one or the other, but not both" (exclusive
  or).  It can also mean "one or the other or both" (inclusive or).  The only
  way you can tell is by context.  In logic, we define or to be inclusive, when
  we use the \lor symbol.

  For if/then, we say A \to B, where A is the *antecedent*, and B is the
  *consequent*.  If has a lot of meanings in English, but in logic, we use
  implication.  It's like a promise.  When you tell your friend "if I finish the
  paper, then I'll come over to your place", the only thing that would offend
  them is if you finished the paper, but did not come over.  Any other situation
  is pretty much fine.

  He says to use plus for exclusive or (if you ever use it), but I prefer \oplus.
  And we don't really use exclusive or.

  - Tomorrow will Rain unless it Snows
    - This is R \lor S.
    - Unless \equiv Or

