#+TITLE: PSCL 101 Notes
#+AUTHOR: Stephen Brennan
#+SETUPFILE: config.setup

* 2016-01-11 Monday

  Intro: stand up, pat your head, jump up and down.  Why did we do that?
  Because the person we thought was the professor told us to.  A bunch of social
  and cognitive "stuff" goes into that.

  Optical illusion pictures - the ones you can see multiple ways.  Your mind
  takes information, organizes, combines, and interprets things in different
  ways.  The same thing happens when you go to movies and discuss them with
  friends.  Or when you relate an experience to someone else.
* 2016-01-13 Wednesday

  Apparently we need iClickers, which sound like another racket.  You can create
  a polling website that you can log into with Case ID's very simply and easily,
  even with Google Docs.  But instead they require students to purchase $40
  remotes!

  Anyway, we did a bunch of iClicker questions.  They were all false.  Then we
  had half of the class look at common sayings and say how many they agree with.
  Then the other half looked at common sayings that mean the opposite, and do
  the same.  The illustration was that we think Psychology is common sense, but
  things we believe to be common sense are frequently wrong.

  Empiricism: the belief that accurate knowledge of the world requires
  observation of it.

  So do research.

  The article we were supposed to read made conclusions on 12 weeks of data from
  a full year study.  So that's bad.

  Elements of the Scientific Process (according to PSCL 101):
  - Theory - a logically consistent model that is supported by data
  - Hypothesis - a proposed explanation for something
  - Variables
